Fix prompt, made it more readable.
* Made the prompt logic easier to understand
* Fix bug with the prompt that__vte_osc7 introduced
* Hide the prompt if there is no room
* Added a short compact version of right prompt
* Remove svn support, I have not used it for years

diff --git a/configure/files/bashrc b/configure/files/bashrc
--- a/configure/files/bashrc
+++ b/configure/files/bashrc
@@ -77,6 +77,8 @@ function pre_prompt() {
 }
 
 function post_prompt() {
+    local ret=$1
+    local compact=$2
 
     local yellow=$(tput setaf 3)
     local white=$(tput setaf 7)
@@ -89,19 +91,15 @@ function post_prompt() {
     if [ -f /usr/bin/git ]; then
         if [ -d .git ] || [ git rev-parse --git-dir 2> /dev/null ]; then
             echo -en "($(git branch | grep \* | awk '{print $2}')"
-            echo -en $yellow
-            echo -en ") $(git config -l | grep remote.origin.url | awk -F : '{print $2}')"
-        fi
-    fi
-
-    if [ -f /usr/bin/svn ]; then
-        if [ -d .svn ]; then
-            echo -n "r$(/usr/bin/svn info | grep Revision: | awk '{print $2}')"
+            echo -en $yellow ")"
+            if ! [ $compact ]; then
+                echo -en " $(git config -l | grep remote.origin.url | awk -F : '{print $2}')"
+            fi
         fi
     fi
 
     echo -en "$white"
-    [ $1 != 0 ] && echo -n " r:$1"
+    [ $ret != 0 ] && echo -n " r:$ret"
     [ -n "$(jobs)" ] && echo -n " j:\j"
 
 
@@ -302,6 +300,25 @@ function krb() {
 
 }
 
+# Clean up the prompt, this is not a complete solution but I know
+# what control seq I use so that makes things simpler.
+function plain() {
+    # sed 1: Remove __vte_osc7 control chars
+    # sed 2: Remove color ^[[33m
+    # sed 3: Remove color \[\033[01;34m\]
+    # sed 4: Remove start/end of non visible chars
+    cat -v - \
+        | sed -r 's/\^.*\^G//g' \
+        | sed -r 's/\^\[\[([0-9]+;)?[0-9]+m//g' \
+        | sed -r 's/\033\[([0-9]{1,2}(;[0-9]{1,2})?)?m//g' \
+        | sed -r 's/\^(A|B)//g'
+}
+
+function size_of_str() {
+    local str=$(cat -)
+    echo ${#str}
+}
+
 ##
 # Set the pre and post prompt
 ##
@@ -311,15 +328,35 @@ function set_prompt() {
         PS1_ORIG=$PS1
     fi
 
+    # Build the right and left side prompt
     local r_prompt="$(post_prompt $?)"
-    local l_prompt="$(pre_prompt)"
+    local l_prompt="$(pre_prompt)${PS1_ORIG}"
 
-    r_prompt_plain="$(echo $r_prompt | sed -r 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g')"
-    _cols_to_move=$(( $COLUMNS - ${#r_prompt_plain} ))
+    # Calculate the visible size, @P is a bash 4.4 feature that expands the prompt
+    local r_prompt_size="$(echo ${r_prompt@P} | plain | size_of_str)"
+    local l_prompt_size="$(echo ${l_prompt@P} | plain | size_of_str)"
 
-    [ ${#l_prompt} -lt 2 ] && l_prompt="${l_prompt% }"
+    if [ $(($COLUMNS - $l_prompt_size)) -le $r_prompt_size ]; then
+        # The available space is to small, try with compact prompt
+        r_prompt="$(post_prompt $? compact)"
+        r_prompt_size="$(echo ${r_prompt@P} | plain | size_of_str)"
+    fi
 
-    PS1="${l_prompt}${PS1_ORIG}\[\033[s\033[$LINES;$(echo -n $_cols_to_move)H${r_prompt}\033[u\]"
+    if [ $(($COLUMNS - $l_prompt_size)) -le $r_prompt_size ]; then
+        # Still no room left for right size prompt, disable it
+        r_prompt=""
+        r_prompt_move=0
+    else
+        # Calculate right prompt offset
+        r_prompt_move=$(($COLUMNS - $r_prompt_size))
+    fi
+
+    # Build prompt
+    PS1="${l_prompt}"                     # Print left side prompt
+    PS1="${PS1}\[\033[s"                  # Save cursor position
+    PS1="${PS1}\033[0;${r_prompt_move}H"  # Move cursor to top right corner
+    PS1="${PS1}${r_prompt}"               # Print right prompt
+    PS1="${PS1}\033[u\]"                  # Return to saved position
 }
 
 ##
